apiVersion: v1
kind: Service
metadata:
  name: hosteszonetestab11
  namespace: default
  labels:
    app: hosteszonetestab11
spec:
  type: ClusterIP
  selector:
    app: hosteszonetestab11
  ports:
    - name: https
      protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hosteszonetestab11
  namespace: default
  labels:
    app: hosteszonetestab11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hosteszonetestab11
  template:
    metadata:
      labels:
        app: hosteszonetestab11
    spec:
      containers:
        - name: hosteszonetestab11-container
          image: codewithdeepak/damnserver:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 512Mi
              cpu: 400m
          env: []
      imagePullSecrets:
        - name: scoutflo-deepaks-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hosteszonetestab11
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: bondre.scoutflo.tech
      http:
        paths:
          - path: /service1
            pathType: Prefix
            backend:
              service:
                name: hosteszonetestab11
                port:
                  number: 5000
    - host: deepaks-service-kls7h.scoutflo.agency
      http:
        paths:
          - path: /service1
            pathType: Prefix
            backend:
              service:
                name: hosteszonetestab11
                port:
                  number: 5000
  tls:
    - hosts:
        - deepaks-service-kls7h.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
