apiVersion: v1
kind: Service
metadata:
  name: eekjrgerkjgberkj
  namespace: default
  labels:
    app: eekjrgerkjgberkj
spec:
  type: ClusterIP
  selector:
    app: eekjrgerkjgberkj
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eekjrgerkjgberkj
  namespace: default
  labels:
    app: eekjrgerkjgberkj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eekjrgerkjgberkj
  template:
    metadata:
      labels:
        app: eekjrgerkjgberkj
    spec:
      containers:
        - name: eekjrgerkjgberkj-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 512Mi
              cpu: 400m
          env: []
      imagePullSecrets:
        - name: scoutflo-satyam-docker-the-latest-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eekjrgerkjgberkj
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: rtrtrtrtrtrt-v3tui.scoutflo.agency
      http:
        paths:
          - path: /test
            pathType: Prefix
            backend:
              service:
                name: eekjrgerkjgberkj
                port:
                  number: 3000
  tls:
    - hosts:
        - rtrtrtrtrtrt-v3tui.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
