apiVersion: v1
kind: Service
metadata:
  name: newtestss
  namespace: default
  labels:
    app: newtestss
spec:
  type: ClusterIP
  selector:
    app: newtestss
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newtestss
  namespace: default
  labels:
    app: newtestss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newtestss
  template:
    metadata:
      labels:
        app: newtestss
    spec:
      containers:
        - name: newtestss-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api
      imagePullSecrets:
        - name: scoutflo-satyam-docker-the-latest-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newtestss
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: atharva.scoutflo.agency
      http:
        paths:
          - path: /service1
            pathType: Prefix
            backend:
              service:
                name: newtestss
                port:
                  number: 3000
    - host: dont-wait-list-zjaso.scoutflo.agency
      http:
        paths:
          - path: /service1
            pathType: Prefix
            backend:
              service:
                name: newtestss
                port:
                  number: 3000
  tls:
    - hosts:
        - dont-wait-list-zjaso.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
    - hosts:
        - atharva.scoutflo.agency
      secretName: wildcard-z088257021cl2sui5i6k9-tls
