apiVersion: v1
kind: Service
metadata:
  name: wkbjkevbekvbkejvb
  namespace: my-new-namespace-7
  labels:
    app: wkbjkevbekvbkejvb
spec:
  type: ClusterIP
  selector:
    app: wkbjkevbekvbkejvb
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wkbjkevbekvbkejvb
  namespace: my-new-namespace-7
  labels:
    app: wkbjkevbekvbkejvb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wkbjkevbekvbkejvb
  template:
    metadata:
      labels:
        app: wkbjkevbekvbkejvb
    spec:
      containers:
        - name: wkbjkevbekvbkejvb-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api
      imagePullSecrets:
        - name: scoutflo-satyam-docker-the-latest-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wkbjkevbekvbkejvb
  namespace: my-new-namespace-7
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: dont-wait-list-5wlgg.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wkbjkevbekvbkejvb
                port:
                  number: 3000
  tls:
    - hosts:
        - dont-wait-list-5wlgg.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
