apiVersion: v1
kind: Service
metadata:
  name: huhhhhhhhh
  namespace: default
  labels:
    app: huhhhhhhhh
spec:
  type: ClusterIP
  selector:
    app: huhhhhhhhh
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: huhhhhhhhh
  namespace: default
  labels:
    app: huhhhhhhhh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huhhhhhhhh
  template:
    metadata:
      labels:
        app: huhhhhhhhh
    spec:
      containers:
        - name: huhhhhhhhh-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api
      imagePullSecrets:
        - name: scoutflo-satyam-docker-the-latest-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: huhhhhhhhh
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/default-backend: huhhhhhhhh
spec:
  rules:
    - host: waitlistdocker-yrlee.scoutflo.agency
      http:
        paths:
          - path: /test
            pathType: Prefix
            backend:
              service:
                name: huhhhhhhhh
                port:
                  number: 3000
  tls:
    - hosts:
        - waitlistdocker-yrlee.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
